### PR TITLE
`zh-Hans` translation (WIP)

### PR DESCRIPTION
**Pull request by LaoshuBaby**
Related Issue: #148

---

Since more than 60% of the work has been carried out, it is recommended that zh-Hans does not need to be integrated through the translation platform of #221, otherwise the current strings will need to be re-imported.

### CODE REVIEW

**Comment by 7h30n3** [comment]
Thanks for your contribution @LaoshuBaby 

IFOPT as an european standard to identify objects in public transport.
For more information on IFOPT please so: https://wiki.openstreetmap.org/wiki/Key%3Aref%3AIFOPT

If you have further question don't hesitate to ask.

**Comment by LaoshuBaby** [comment]
> IFOPT as an european standard to identify objects in public transport.
> For more information on IFOPT please so: https://wiki.openstreetmap.org/wiki/Key%3Aref%3AIFOPT

No wonder I've never seen it, is it possible to omit them in a translation of Simplified Chinese? (Because we can sure that China will not use IFOPT, CR will only use their own internal identifier system)

**Comment by 7h30n3** [comment]
@LaoshuBaby I just wanna ask if the PR is ready for review or if you are planning to make some more edits.

**Comment by LaoshuBaby** [comment]
> @LaoshuBaby I just wanna ask if the PR is ready for review or if you are planning to make some more edits.

Sorry, I don’t have a lot of free time, and sometimes I forget to adjust some schedules (so I will finish this nearly a thousand lines of text very slowly)
Do not worry!

**Comment by 7h30n3** [comment]
No hurry, we are just planning a release of a minor update and asked ourselves if this PR could also be in it.

**Comment by LaoshuBaby** [comment]
@7h30n3 
What is width of cycle, opening and spacing of cycle barrier? Can you give me a example that define those 3 thing in a picture?
I'm sorry, this may be due to my lack of life experience in this area.

**Comment by 7h30n3** [comment]
> @7h30n3
> 
> ~Q1. What is width of cycle, opening and spacing of cycle barrier? Can you give me a example that define those 3 thing in a picture?~
> 
> OK I found example picture in image folder ([osmwiki](https://wiki.openstreetmap.org/wiki/Key:cycle_barrier) only tell me what about "single" or "double"):
> [width](https://github.com/OPENER-next/OpenStop/blob/93e174a604e3f231cb19b60e92e469de5d86884b/assets/question_catalog/images/cycle_barrier_width.png) 	[opening](https://github.com/OPENER-next/OpenStop/blob/93e174a604e3f231cb19b60e92e469de5d86884b/assets/question_catalog/images/cycle_barrier_double_opening.png) 	[spacing](https://github.com/OPENER-next/OpenStop/blob/93e174a604e3f231cb19b60e92e469de5d86884b/assets/question_catalog/images/cycle_barrier_double_spacing.png)
>  	 	
> 
> But I also still have other questions, I'm sorry, this may be due to my lack of life experience in this area :
> 
> Q2. What is Portable Lift?
> 
> Q3. Is this can be seen as have both passenger information and dynamic timetable display?
> 
> Image from https://m.bbtnews.com.cn/content/60/94/277667.html

Hi @LaoshuBaby Sorry for the late answer.
Q2:
What a portable lift is, can be seen here: https://wiki.openstreetmap.org/wiki/Key:platform_lift:portable
If you need further clearification please let me know.

Q3:
I actually can't tell you what this is. My Chinese isn't very good.
If the display shows only the depatures from ONE platform it is an passenger information display.
If the display shows the departures from multiple platforms respectively the whole bus station it is a dynamic timetable display.

**Comment by 7h30n3** [comment]
@LaoshuBaby We are now using weblate to translate OpenStop in different languages. 
It would be very convenient when you could upload you translations there: https://hosted.weblate.org/projects/openstop/ for the respective components.
I think this cloud help you: https://docs.weblate.org/en/latest/user/files.html#uploading-translations

**Comment by 7h30n3** [comment]
I uploaded your translation to weblate while giving you credit. If you or anybody else want to refine the translation, it can now be done here: https://hosted.weblate.org/projects/openstop/-/zh_Hans/

Closing this PR.

**Comment by LaoshuBaby** [comment]
Sorry, I came too late
I just discovered this series of emails while clearing out unread emails, and I must admit that I haven't taken the time to openstop since the end of last year, which is my fault.
When I just saw the first email, I thought maybe you could merge these commits first and then synchronize weblate with them. But it seems that this is no longer possible.

It may be a pity for me not to record every change history in the form of commit, but this is indeed because I failed to complete the work in time.

**Pull request closed without merging**
