### PR TITLE
Clarify description for automatic door question

### PR DESCRIPTION
**Pull request by FloEdelmann**

### CODE REVIEW

**Comment by 7h30n3** [comment]
Thank you for the contribution.
If you could just remove the "ggf.". I think the "könnte" (could) already describes the button press as optional.

**Comment by Robbendebiene** [comment]
What do you think about changing it to: "Bei der automatischen Öffnung wird die Tür von einer Mechanik geöffnet. Diese kann durch einen Sensor oder Taster ausgelöst werden."

**Comment by 7h30n3** [comment]
> What do you think about changing it to: "Bei der automatischen Öffnung wird die Tür von einer Mechanik geöffnet. Diese kann durch einen Sensor oder Taster ausgelöst werden."

That's even better 👍

**Comment by FloEdelmann** [comment]
That would technically not be correct for the revolving door, which does not need any trigger at all.

**Comment by Robbendebiene** [comment]
> That would technically not be correct for the revolving door, which does not need any trigger at all.

Good point. The `continuous` value never felt like a good fit for a broad door question. So maybe we could have a more radical change and add extra questions for the revolving door:

1. if `door=revolving` we ask whether it turns automatically
2. if `door=revolving && automatic_door=yes` we ask whether it turns continuously, on button press or on motion sensor.

Then for every other door type (where continuously doesn't make sense) we only ask for "on button press" and "on motion sensor".
Maybe we should also rephrase the question from "is it an automatic door" to "can it be opened automatically" since some doors can be opened by button and by hand.

**Comment by Robbendebiene** [comment]
This has been resolved by #186

**Pull request closed without merging**
